name: Deploy to Github Pages
run-name: ${{ github.actor }} is deploying to https://timothy-ch-cheung.github.io/game-component-demos
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public