name: Deploy to Github Pages
run-name: ${{ github.actor }} is deploying to https://timothy-ch-cheung.github.io/game-component-demos
on:
  push:
    branches:
      - main
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm ci
      - run: npm run build

      - name: Deploy
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build